### ISSUE TITLE
Question: what is the source of this list? Does discord really not provide official specification for their rest API?

### ISSUE THREAD

**Issue by klesun** [GregTCLTK/Discord-Api-Endpoints#14]
Hi, thanks for your work, it's the first thing resembling something that can be used without installing any opiniated libs for my environment.

Did you just scrape those endpoints by analyzing Network traffic? Does Discord discourage using their API through plain rest requests?

**Comment by klesun** [comment]
Oh, phew, the official documentation for rest endpoints does exist, it's just categorized by subject and put in the bottom of the page:
https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log

**Comment by greg6775** [comment]
Some endpoints listed here are also listed in the official Discord API Docs. However, Discord does not disclose all of their endpoints. That's why I put them in this repository.
