### ISSUE TITLE
New superx value

### ISSUE THREAD

**Issue by hyiamailapi** [GregTCLTK/Discord-Api-Endpoints#20]
gang yall only need this
headers = {
   "authorization":token,
   "x-super-properties":"ewogICJvcyI6ICJXaW5kb3dzIiwKICAiY2xpZW50X2J1aWxkX251bWJlciI6IDI3NTIwOAp9"
}

**Comment by greg6775** [comment]
I've already added detailed information regarding this new header [in the readme.](https://github.com/GregTCLTK/Discord-Api-Endpoints#x-super-properties-header)
